// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/server/service.proto

package starlingfoundries_operator_server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusResp_Status int32

const (
	StatusResp_UNDEFINED StatusResp_Status = 0
	StatusResp_RECIEVED  StatusResp_Status = 1
	StatusResp_PROCESSED StatusResp_Status = 2
	StatusResp_REJECTED  StatusResp_Status = 3
)

var StatusResp_Status_name = map[int32]string{
	0: "UNDEFINED",
	1: "RECIEVED",
	2: "PROCESSED",
	3: "REJECTED",
}

var StatusResp_Status_value = map[string]int32{
	"UNDEFINED": 0,
	"RECIEVED":  1,
	"PROCESSED": 2,
	"REJECTED":  3,
}

func (x StatusResp_Status) String() string {
	return proto.EnumName(StatusResp_Status_name, int32(x))
}

func (StatusResp_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0ec0399e66a248e4, []int{2, 0}
}

type ByteArray struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ByteArray) Reset()         { *m = ByteArray{} }
func (m *ByteArray) String() string { return proto.CompactTextString(m) }
func (*ByteArray) ProtoMessage()    {}
func (*ByteArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0399e66a248e4, []int{0}
}

func (m *ByteArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ByteArray.Unmarshal(m, b)
}
func (m *ByteArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ByteArray.Marshal(b, m, deterministic)
}
func (m *ByteArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ByteArray.Merge(m, src)
}
func (m *ByteArray) XXX_Size() int {
	return xxx_messageInfo_ByteArray.Size(m)
}
func (m *ByteArray) XXX_DiscardUnknown() {
	xxx_messageInfo_ByteArray.DiscardUnknown(m)
}

var xxx_messageInfo_ByteArray proto.InternalMessageInfo

func (m *ByteArray) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Client struct {
	Key                  *ByteArray `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Client) Reset()         { *m = Client{} }
func (m *Client) String() string { return proto.CompactTextString(m) }
func (*Client) ProtoMessage()    {}
func (*Client) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0399e66a248e4, []int{1}
}

func (m *Client) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Client.Unmarshal(m, b)
}
func (m *Client) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Client.Marshal(b, m, deterministic)
}
func (m *Client) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Client.Merge(m, src)
}
func (m *Client) XXX_Size() int {
	return xxx_messageInfo_Client.Size(m)
}
func (m *Client) XXX_DiscardUnknown() {
	xxx_messageInfo_Client.DiscardUnknown(m)
}

var xxx_messageInfo_Client proto.InternalMessageInfo

func (m *Client) GetKey() *ByteArray {
	if m != nil {
		return m.Key
	}
	return nil
}

type StatusResp struct {
	SenderPkey *ByteArray `protobuf:"bytes,1,opt,name=sender_pkey,json=senderPkey,proto3" json:"sender_pkey,omitempty"`
	//tranid should be the chain-addressable transaction id for use in ex: viewblock.io
	Tranid               []byte            `protobuf:"bytes,2,opt,name=tranid,proto3" json:"tranid,omitempty"`
	Status               StatusResp_Status `protobuf:"varint,3,opt,name=status,proto3,enum=starlingfoundries.operator.server.StatusResp_Status" json:"status,omitempty"`
	Nonce                uint64            `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StatusResp) Reset()         { *m = StatusResp{} }
func (m *StatusResp) String() string { return proto.CompactTextString(m) }
func (*StatusResp) ProtoMessage()    {}
func (*StatusResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0399e66a248e4, []int{2}
}

func (m *StatusResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResp.Unmarshal(m, b)
}
func (m *StatusResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResp.Marshal(b, m, deterministic)
}
func (m *StatusResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResp.Merge(m, src)
}
func (m *StatusResp) XXX_Size() int {
	return xxx_messageInfo_StatusResp.Size(m)
}
func (m *StatusResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResp.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResp proto.InternalMessageInfo

func (m *StatusResp) GetSenderPkey() *ByteArray {
	if m != nil {
		return m.SenderPkey
	}
	return nil
}

func (m *StatusResp) GetTranid() []byte {
	if m != nil {
		return m.Tranid
	}
	return nil
}

func (m *StatusResp) GetStatus() StatusResp_Status {
	if m != nil {
		return m.Status
	}
	return StatusResp_UNDEFINED
}

func (m *StatusResp) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

//Empty only requires the calling user's pubkey
type Empty struct {
	Pubkey               *ByteArray `protobuf:"bytes,1,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0399e66a248e4, []int{3}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func (m *Empty) GetPubkey() *ByteArray {
	if m != nil {
		return m.Pubkey
	}
	return nil
}

type QueueID struct {
	QueueID              uint32   `protobuf:"varint,1,opt,name=queueID,proto3" json:"queueID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueueID) Reset()         { *m = QueueID{} }
func (m *QueueID) String() string { return proto.CompactTextString(m) }
func (*QueueID) ProtoMessage()    {}
func (*QueueID) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0399e66a248e4, []int{4}
}

func (m *QueueID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueueID.Unmarshal(m, b)
}
func (m *QueueID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueueID.Marshal(b, m, deterministic)
}
func (m *QueueID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueueID.Merge(m, src)
}
func (m *QueueID) XXX_Size() int {
	return xxx_messageInfo_QueueID.Size(m)
}
func (m *QueueID) XXX_DiscardUnknown() {
	xxx_messageInfo_QueueID.DiscardUnknown(m)
}

var xxx_messageInfo_QueueID proto.InternalMessageInfo

func (m *QueueID) GetQueueID() uint32 {
	if m != nil {
		return m.QueueID
	}
	return 0
}

//this object is injected straight into the code field of the encapsulating transaction
type CheckTransaction struct {
	Version      uint32     `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Senderpubkey *ByteArray `protobuf:"bytes,2,opt,name=senderpubkey,proto3" json:"senderpubkey,omitempty"`
	Toaddr       []byte     `protobuf:"bytes,3,opt,name=toaddr,proto3" json:"toaddr,omitempty"`
	Amount       *ByteArray `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee          *ByteArray `protobuf:"bytes,5,opt,name=fee,proto3" json:"fee,omitempty"`
	OperatorAddr []byte     `protobuf:"bytes,6,opt,name=operatorAddr,proto3" json:"operatorAddr,omitempty"`
	//this nonce is account-specific within the scilla contract. The encapsulating transaction will have a nonce from the operator's wallet.
	Nonce                uint64     `protobuf:"varint,7,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Signature            *ByteArray `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CheckTransaction) Reset()         { *m = CheckTransaction{} }
func (m *CheckTransaction) String() string { return proto.CompactTextString(m) }
func (*CheckTransaction) ProtoMessage()    {}
func (*CheckTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0399e66a248e4, []int{5}
}

func (m *CheckTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckTransaction.Unmarshal(m, b)
}
func (m *CheckTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckTransaction.Marshal(b, m, deterministic)
}
func (m *CheckTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckTransaction.Merge(m, src)
}
func (m *CheckTransaction) XXX_Size() int {
	return xxx_messageInfo_CheckTransaction.Size(m)
}
func (m *CheckTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_CheckTransaction proto.InternalMessageInfo

func (m *CheckTransaction) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *CheckTransaction) GetSenderpubkey() *ByteArray {
	if m != nil {
		return m.Senderpubkey
	}
	return nil
}

func (m *CheckTransaction) GetToaddr() []byte {
	if m != nil {
		return m.Toaddr
	}
	return nil
}

func (m *CheckTransaction) GetAmount() *ByteArray {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *CheckTransaction) GetFee() *ByteArray {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *CheckTransaction) GetOperatorAddr() []byte {
	if m != nil {
		return m.OperatorAddr
	}
	return nil
}

func (m *CheckTransaction) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *CheckTransaction) GetSignature() *ByteArray {
	if m != nil {
		return m.Signature
	}
	return nil
}

type OperatorTargetResp struct {
	ContractAddr         []byte   `protobuf:"bytes,1,opt,name=contractAddr,proto3" json:"contractAddr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatorTargetResp) Reset()         { *m = OperatorTargetResp{} }
func (m *OperatorTargetResp) String() string { return proto.CompactTextString(m) }
func (*OperatorTargetResp) ProtoMessage()    {}
func (*OperatorTargetResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0399e66a248e4, []int{6}
}

func (m *OperatorTargetResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatorTargetResp.Unmarshal(m, b)
}
func (m *OperatorTargetResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatorTargetResp.Marshal(b, m, deterministic)
}
func (m *OperatorTargetResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatorTargetResp.Merge(m, src)
}
func (m *OperatorTargetResp) XXX_Size() int {
	return xxx_messageInfo_OperatorTargetResp.Size(m)
}
func (m *OperatorTargetResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatorTargetResp.DiscardUnknown(m)
}

var xxx_messageInfo_OperatorTargetResp proto.InternalMessageInfo

func (m *OperatorTargetResp) GetContractAddr() []byte {
	if m != nil {
		return m.ContractAddr
	}
	return nil
}

type FeeResp struct {
	Fee                  *ByteArray `protobuf:"bytes,1,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FeeResp) Reset()         { *m = FeeResp{} }
func (m *FeeResp) String() string { return proto.CompactTextString(m) }
func (*FeeResp) ProtoMessage()    {}
func (*FeeResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0ec0399e66a248e4, []int{7}
}

func (m *FeeResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FeeResp.Unmarshal(m, b)
}
func (m *FeeResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FeeResp.Marshal(b, m, deterministic)
}
func (m *FeeResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeeResp.Merge(m, src)
}
func (m *FeeResp) XXX_Size() int {
	return xxx_messageInfo_FeeResp.Size(m)
}
func (m *FeeResp) XXX_DiscardUnknown() {
	xxx_messageInfo_FeeResp.DiscardUnknown(m)
}

var xxx_messageInfo_FeeResp proto.InternalMessageInfo

func (m *FeeResp) GetFee() *ByteArray {
	if m != nil {
		return m.Fee
	}
	return nil
}

func init() {
	proto.RegisterEnum("starlingfoundries.operator.server.StatusResp_Status", StatusResp_Status_name, StatusResp_Status_value)
	proto.RegisterType((*ByteArray)(nil), "starlingfoundries.operator.server.ByteArray")
	proto.RegisterType((*Client)(nil), "starlingfoundries.operator.server.Client")
	proto.RegisterType((*StatusResp)(nil), "starlingfoundries.operator.server.StatusResp")
	proto.RegisterType((*Empty)(nil), "starlingfoundries.operator.server.Empty")
	proto.RegisterType((*QueueID)(nil), "starlingfoundries.operator.server.queueID")
	proto.RegisterType((*CheckTransaction)(nil), "starlingfoundries.operator.server.CheckTransaction")
	proto.RegisterType((*OperatorTargetResp)(nil), "starlingfoundries.operator.server.OperatorTargetResp")
	proto.RegisterType((*FeeResp)(nil), "starlingfoundries.operator.server.FeeResp")
}

func init() { proto.RegisterFile("rpc/server/service.proto", fileDescriptor_0ec0399e66a248e4) }

var fileDescriptor_0ec0399e66a248e4 = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0x41, 0x6f, 0xda, 0x4c,
	0x10, 0xfd, 0x0c, 0xc4, 0xc0, 0x84, 0x44, 0x68, 0xf5, 0xa9, 0xb2, 0xb8, 0x94, 0xba, 0x17, 0x5a,
	0xb5, 0x54, 0x22, 0xad, 0xd4, 0x53, 0xa5, 0x04, 0x9b, 0x94, 0x28, 0x24, 0xc8, 0xd0, 0x5e, 0xab,
	0x8d, 0x3d, 0x50, 0x0b, 0xb2, 0xeb, 0xec, 0xae, 0x23, 0xf1, 0x5b, 0x7a, 0x6b, 0xff, 0x68, 0xe5,
	0xb5, 0x0d, 0xa1, 0xaa, 0x54, 0xe3, 0x13, 0x3b, 0xde, 0x99, 0x37, 0x8f, 0x37, 0x6f, 0x6c, 0xb0,
	0x44, 0xe4, 0xbf, 0x93, 0x28, 0x1e, 0x51, 0xe8, 0x9f, 0xd0, 0xc7, 0x7e, 0x24, 0xb8, 0xe2, 0xe4,
	0x85, 0x54, 0x54, 0xac, 0x43, 0xb6, 0x5c, 0xf0, 0x98, 0x05, 0x22, 0x44, 0xd9, 0xe7, 0x11, 0x0a,
	0xaa, 0xb8, 0xe8, 0xa7, 0x05, 0xf6, 0x73, 0x68, 0x5e, 0x6c, 0x14, 0x9e, 0x0b, 0x41, 0x37, 0x84,
	0x40, 0x2d, 0xa0, 0x8a, 0x5a, 0x46, 0xd7, 0xe8, 0xb5, 0x3c, 0x7d, 0xb6, 0x3f, 0x83, 0x39, 0x5c,
	0x87, 0xc8, 0x14, 0xf9, 0x04, 0xd5, 0x15, 0x6e, 0xf4, 0xe5, 0xf1, 0xe0, 0x4d, 0xff, 0x9f, 0xd8,
	0xfd, 0x2d, 0xb0, 0x97, 0x14, 0xda, 0x3f, 0x2a, 0x00, 0x33, 0x45, 0x55, 0x2c, 0x3d, 0x94, 0x11,
	0x99, 0xc0, 0xb1, 0x44, 0x16, 0xa0, 0xf8, 0x16, 0x95, 0x85, 0x85, 0x14, 0x60, 0xba, 0xc2, 0x0d,
	0x79, 0x06, 0xa6, 0x12, 0x94, 0x85, 0x81, 0x55, 0xd1, 0xec, 0xb3, 0x88, 0x5c, 0x83, 0x29, 0x75,
	0x53, 0xab, 0xda, 0x35, 0x7a, 0xa7, 0x83, 0xf7, 0x05, 0x3a, 0xec, 0x58, 0xe6, 0xc7, 0x0c, 0x83,
	0xfc, 0x0f, 0x47, 0x8c, 0x33, 0x1f, 0xad, 0x5a, 0xd7, 0xe8, 0xd5, 0xbc, 0x34, 0xb0, 0x2f, 0xc0,
	0x4c, 0xf3, 0xc8, 0x09, 0x34, 0xbf, 0xdc, 0x38, 0xee, 0x68, 0x7c, 0xe3, 0x3a, 0xed, 0xff, 0x48,
	0x0b, 0x1a, 0x9e, 0x3b, 0x1c, 0xbb, 0x5f, 0x5d, 0xa7, 0x6d, 0x24, 0x97, 0x53, 0xef, 0x76, 0xe8,
	0xce, 0x66, 0xae, 0xd3, 0xae, 0xa4, 0x97, 0x57, 0xee, 0x70, 0xee, 0x3a, 0xed, 0xaa, 0x3d, 0x81,
	0x23, 0xf7, 0x3e, 0x52, 0x1b, 0xe2, 0x80, 0x19, 0xc5, 0x77, 0x65, 0x25, 0xc9, 0x6a, 0xed, 0x97,
	0x50, 0x7f, 0x88, 0x31, 0xc6, 0xb1, 0x43, 0xac, 0xed, 0x51, 0x23, 0x9e, 0x78, 0x79, 0x68, 0xff,
	0xac, 0x42, 0x7b, 0xf8, 0x1d, 0xfd, 0xd5, 0x5c, 0x50, 0x26, 0xa9, 0xaf, 0x42, 0xce, 0x92, 0xf4,
	0x47, 0x14, 0x32, 0xe4, 0x2c, 0x4f, 0xcf, 0x42, 0x32, 0x85, 0x56, 0x2a, 0x78, 0xc6, 0xaf, 0x52,
	0x82, 0xdf, 0x1e, 0x82, 0x1e, 0x1a, 0xa7, 0x41, 0x20, 0xf4, 0x70, 0x92, 0xa1, 0xe9, 0x28, 0xd1,
	0x80, 0xde, 0xf3, 0x98, 0x29, 0xad, 0xf3, 0xc1, 0x1a, 0xa4, 0xb5, 0x89, 0x61, 0x17, 0x88, 0xd6,
	0x51, 0x19, 0xc3, 0x2e, 0x10, 0x89, 0x0d, 0xad, 0x3c, 0xe3, 0x3c, 0xe1, 0x68, 0x6a, 0x8e, 0x7b,
	0xcf, 0x76, 0x86, 0xa8, 0x3f, 0x31, 0x04, 0xb9, 0x82, 0xa6, 0x0c, 0x97, 0x8c, 0xaa, 0x58, 0xa0,
	0xd5, 0x28, 0xd1, 0x7f, 0x57, 0x6e, 0x7f, 0x04, 0x72, 0x9b, 0xe5, 0xcd, 0xa9, 0x58, 0xa2, 0xd2,
	0xdb, 0x63, 0x43, 0xcb, 0xe7, 0x4c, 0x09, 0xea, 0x2b, 0xcd, 0x2d, 0x5d, 0xd9, 0xbd, 0x67, 0xf6,
	0x18, 0xea, 0x23, 0x44, 0x9d, 0x9e, 0x49, 0x61, 0x94, 0x94, 0x62, 0xf0, 0xab, 0x06, 0x8d, 0x9c,
	0x05, 0x59, 0x43, 0x73, 0x86, 0x2c, 0xd0, 0xce, 0x21, 0x67, 0x05, 0xc0, 0xfe, 0xf4, 0x58, 0xe7,
	0x75, 0x81, 0xa2, 0xdc, 0xbe, 0xfe, 0x76, 0xb9, 0x0e, 0xa8, 0xea, 0xbc, 0x3d, 0x68, 0xcd, 0x09,
	0x03, 0x72, 0x89, 0xea, 0x9a, 0x4a, 0xf5, 0x74, 0x15, 0x5e, 0x15, 0xf9, 0x6f, 0xfa, 0xe5, 0x78,
	0x68, 0xbf, 0x07, 0x38, 0xdd, 0x1f, 0x2a, 0xe9, 0x15, 0x00, 0xd0, 0x2f, 0x88, 0xce, 0x87, 0x02,
	0x99, 0x7f, 0x71, 0x0c, 0x85, 0xe6, 0x25, 0xaa, 0x49, 0xc8, 0x46, 0x88, 0x07, 0x74, 0x2b, 0x22,
	0x7a, 0xe6, 0xb2, 0x3b, 0x53, 0x7f, 0x76, 0xce, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x5a, 0xa2,
	0xfb, 0x78, 0x92, 0x06, 0x00, 0x00,
}
